spring:
  neo4j:
    #uri: neo4j+s://ab6bbbca.databases.neo4j.io
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      #password: qeARmHp0V_OSxravPEZC-yot-unRoFsI5YgYy5Ws-Hs
      password: local123
  data:
    neo4j:
      database: neo4j

logging.level.org.springframework.data.neo4j: DEBUG

